<template>
  <el-card shadow="never" class="claim-card">
    <el-row align="middle">
      <span>Claimable VTHO</span>
      <el-popover
        placement="bottom"
        :width="210"
        trigger="click"
        content="Liquidity providers can claim additional VTHO generated by providing VET asset."
      >
        <template #reference>
          <el-icon style="display: flex; margin-left: 5px;">
            <Warning />
          </el-icon>
        </template>
      </el-popover>
    </el-row>
    <template v-if="!addr">
      <div style="color: #7d8087; font-size: 15px; padding: 10px 0">Connect to a wallet to check your claimable VTHO.</div>
      <el-button style="margin-top: 20px; width: 180px" type="primary" @click="connect">Connect wallet</el-button>
    </template>
    <template v-else>
      <div style="color: #252122; font-size: 40px;">
        {{vtho}}
      </div>
      <el-button style="margin-top: 20px; width: 180px;" type="primary" @click="claim">Claim</el-button>
    </template>
    <TxInfoDialog
      type="claim"
      ref="txdialog"
      :contents="contents"
      :confirmMsg="confirmMsg"
      :onConfirm="onConfirm"
    />
  </el-card>
</template>
<script lang="ts">
import { defineComponent } from 'vue'
import TxInfoDialog from './txInfoDialog.vue'
import { fromWei } from '../utils'
import Connex from '@vechain/connex'
import BigNumber from 'bignumber.js'

type Item = {
  token: 'vet' | 'vtho'
  amount: string
}
export default defineComponent({
  name: 'claim',
  components: {
    TxInfoDialog
  },
  props: {
    addr: String
  },
  data: () => {
    return {
      contents: [] as Item[],
      confirmMsg: 'Output is estimated.'
    }
  },
  computed: {
    vtho (): string {
      const temp = new BigNumber(fromWei(this.$state.lpToken.claim))
      if (temp.isNaN() || temp.isZero()) {
        return '0.00'
      } else if (temp.lt(0.001)) {
        return '< 0.001'
      } else if (temp.lt(1)) {
        return temp.toFixed(5, 0)
      } else {
        return temp.toFixed(3, 1)
      }
    }
  },
  methods: {
    connect () {
      this.$emit('connect')
    },
    async onConfirm (): Promise<Connex.Vendor.TxResponse | void | unknown> {
      if (!this.addr) {
        this.$emit('connect')
        return
      }
      const clause = this.$vv.claim(this.addr)
      const myPromise = new Promise((resolve, reject) => {
        setTimeout(() => {
          reject(new Error('timeout'))
        }, 50000)
      })
      try {
        return Promise.race([
          myPromise,
          await this.$connex.vendor.sign('tx', [clause]).signer(this.addr).request()
        ])
      } catch (error) {
        console.log(error)
      } finally {
      }
    },
    async claim () {
      this.contents = [
        {
          token: 'vtho',
          amount: this.vtho
        }
      ]
      ;(this.$refs.txdialog as typeof TxInfoDialog).open()
    }
  }
})
</script>
<style scoped>
.claim-card {
  height: 220px;
  margin: auto;
  width: 390px;
  padding: 20px 60px 20px 20px;
  box-sizing: border-box;
  background-image: url(../assets/vtho-bg.svg);
  background-repeat: no-repeat;
  background-position: right bottom;
}
</style>
